name: Execute

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'CS2 Branch'
                required: false
                default: 'public'
                type: string
    repository_dispatch:

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    execute:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        environment: Execute
        steps:
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                remove-dotnet: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
            - name: Generate a token
              id: generate-token
              uses: actions/create-github-app-token@v1
              with:
                app-id: ${{ secrets.GH_APP_ID }}
                private-key: ${{ secrets.GH_APP_PK }}
                owner: ${{ github.repository_owner }}
            - name: Hide token
              run: echo "::add-mask::$GITHUB_TOKEN"
              env:
                GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
            - name: Execute script
              uses: docker://ghcr.io/lifeismana/gametracking-cs2:latest
              env:
                GIT_NAME: ${{ secrets.GIT_NAME }}
                GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
                STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
                STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
                GPG_KEY: ${{ secrets.GPG_KEY }}
                GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
                GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
                GITHUB_APP_ID: ${{ secrets.GH_APP_ID }}
                STEAM_BRANCH: ${{ github.event.inputs.branch }}
